#!/usr/bin/env zsh
# Load user-config.yml into USER_NAME, USER_EMAIL, GITHUB_USERNAME.
# Usage: load_user_config /path/to/user-config.yml

load_user_config() {
    local config_file="$1"
    local -a fields=()

    if [[ ! -f "$config_file" ]]; then
        echo "Missing $config_file — copy user-config.example.yml to user-config.yml" >&2
        return 1
    fi

    if [[ ! -x /usr/bin/ruby ]]; then
        echo "install requires /usr/bin/ruby to read user-config.yml" >&2
        return 1
    fi

    if ! fields=("${(@f)$(/usr/bin/ruby -ryaml -e '
        d = YAML.load_file(ARGV[0])
        u = d.fetch("user")
        gh = d.fetch("github")
        [u.fetch("name"), u.fetch("email"), gh.fetch("username")].each do |v|
          v = v.to_s.strip
          abort "user-config.yml: name, email, and github.username must be non-empty" if v.empty?
          puts v
        end
    ' "$config_file")}"); then
        return 1
    fi

    if (( ${#fields[@]} != 3 )); then
        echo "user-config.yml: expected user.name, user.email, github.username" >&2
        return 1
    fi

    USER_NAME="$fields[1]"
    USER_EMAIL="$fields[2]"
    GITHUB_USERNAME="$fields[3]"
}

apply_git_user_from_config() {
    git config --global user.name "$USER_NAME"
    git config --global user.email "$USER_EMAIL"
}

write_github_env() {
    local dest="$1"
    mkdir -p "$(dirname "$dest")"
    {
        print -r -- "# Generated by install.sh from user-config.yml — do not edit"
        print -r -- "export GITHUB_USERNAME=${(q)GITHUB_USERNAME}"
    } >"$dest"
}

apply_github_from_config() {
    git config --global \
        url."git@github.com:${GITHUB_USERNAME}/".insteadOf \
        "https://github.com/${GITHUB_USERNAME}/"

    if command -v gh >/dev/null 2>&1; then
        gh config set git_protocol ssh -h github.com 2>/dev/null || true
    fi
}
