#!/usr/bin/env zsh
# Load user-config.yml into USER_NAME, USER_EMAIL, GITHUB_USERNAME.
# Usage: ensure_user_config /path/to/user-config.yml && load_user_config /path/to/user-config.yml

prompt_nonempty() {
    local var_name="$1" prompt_text="$2" value=""
    while true; do
        read -r "value?${prompt_text}: " </dev/tty
        value="${value#"${value%%[![:space:]]*}"}"
        value="${value%"${value##*[![:space:]]}"}"
        if [[ -n "$value" ]]; then
            eval "${var_name}=\$value"
            return 0
        fi
        echo "Value cannot be empty." >/dev/tty
    done
}

write_user_config_file() {
    local config_file="$1" name="$2" email="$3" github_user="$4"

    if [[ ! -x /usr/bin/ruby ]]; then
        echo "install requires /usr/bin/ruby to write user-config.yml" >&2
        return 1
    fi

    UC_NAME="$name" UC_EMAIL="$email" UC_GITHUB="$github_user" \
        /usr/bin/ruby -ryaml -e '
          require "yaml"
          File.write(
            ARGV[0],
            {
              "user" => {"name" => ENV.fetch("UC_NAME"), "email" => ENV.fetch("UC_EMAIL")},
              "github" => {"username" => ENV.fetch("UC_GITHUB")}
            }.to_yaml
          )
        ' "$config_file"
}

ensure_user_config() {
    local config_file="$1"
    local name="" email="" github_user=""

    if [[ -f "$config_file" ]]; then
        return 0
    fi

    if [[ ! -e /dev/tty ]]; then
        echo "Missing $config_file and no TTY to create it interactively." >&2
        echo "Copy user-config.example.yml to user-config.yml and edit, or run ./install.sh in a terminal." >&2
        return 1
    fi

    {
        print -r -- ""
        print -r -- "user-config.yml not found."
        print -r -- "Enter the values used for Git, SSH, and GitHub (written to ${config_file:t})."
        print -r -- ""
    } >/dev/tty

    prompt_nonempty name "Full name (user.name)"
    prompt_nonempty email "Email (user.email)"
    prompt_nonempty github_user "GitHub username (github.username)"

    write_user_config_file "$config_file" "$name" "$email" "$github_user"
    echo "Wrote $config_file" >/dev/tty
}

load_user_config() {
    local config_file="$1"
    local -a fields=()

    if [[ ! -f "$config_file" ]]; then
        echo "Missing $config_file" >&2
        return 1
    fi

    if [[ ! -x /usr/bin/ruby ]]; then
        echo "install requires /usr/bin/ruby to read user-config.yml" >&2
        return 1
    fi

    if ! fields=("${(@f)$(/usr/bin/ruby -ryaml -e '
        d = YAML.load_file(ARGV[0])
        u = d.fetch("user")
        gh = d.fetch("github")
        [u.fetch("name"), u.fetch("email"), gh.fetch("username")].each do |v|
          v = v.to_s.strip
          abort "user-config.yml: name, email, and github.username must be non-empty" if v.empty?
          puts v
        end
    ' "$config_file")}"); then
        return 1
    fi

    if (( ${#fields[@]} != 3 )); then
        echo "user-config.yml: expected user.name, user.email, github.username" >&2
        return 1
    fi

    USER_NAME="$fields[1]"
    USER_EMAIL="$fields[2]"
    GITHUB_USERNAME="$fields[3]"
}

git_config_set_if_needed() {
    local key="$1" expected="$2" current=""

    current="$(git config --global "$key" 2>/dev/null || true)"
    if [[ "$current" == "$expected" ]]; then
        return 0
    fi
    git config --global "$key" "$expected"
}

apply_git_user_from_config() {
    git_config_set_if_needed user.name "$USER_NAME"
    git_config_set_if_needed user.email "$USER_EMAIL"
}

write_github_env() {
    local dest="$1" new_content=""

    new_content="$(print -r -- "# Generated by install.sh from user-config.yml — do not edit"
print -r -- "export GITHUB_USERNAME=${(q)GITHUB_USERNAME}")"

    if [[ -f "$dest" ]] && [[ "$(<"$dest")" == "$new_content" ]]; then
        return 0
    fi

    mkdir -p "$(dirname "$dest")"
    print -r -- "$new_content" >"$dest"
}

apply_github_from_config() {
    local insteadof="https://github.com/${GITHUB_USERNAME}/"
    local url_key="url.git@github.com:${GITHUB_USERNAME}/.insteadof"
    local current="" gh_protocol=""

    current="$(git config --global --get "$url_key" 2>/dev/null || true)"
    if [[ "$current" != "$insteadof" ]]; then
        git config --global \
            url."git@github.com:${GITHUB_USERNAME}/".insteadOf \
            "$insteadof"
    fi

    if command -v gh >/dev/null 2>&1; then
        gh_protocol="$(gh config get git_protocol -h github.com 2>/dev/null || true)"
        if [[ "$gh_protocol" != "ssh" ]]; then
            gh config set git_protocol ssh -h github.com 2>/dev/null || true
        fi
    fi
}
